<?php $employees = $block->getAllEmployees();?>

<?php if(count($employees)>0):?>
    <table border="1">
        <tr>
            <th><?=__("ID")?></th>
            <th><?=__("First Name")?></th>
            <th><?=__("Last Name")?></th>
            <th><?=__("Email Id")?></th>
        </tr>
        <?php foreach($employees as $employee):?>
            <tr>
                <td><?=$employee->getEmployeeId()?></td>
                <td><?=$employee->getFirstName()?></td>
                <td><?=$employee->getLastName()?></td>
                <td><?=$employee->getEmail()?></td>
            </tr>
        <?php endforeach;?>
    </table>
<?php else:?>
    <h1><?=__("You have no employee yet:")?></h1>
<?php endif;?>
<hr/>